Gitlab integration
Ensembl/ensembl-web-resolver pull request #8
Opened 2024-08-19 12:05 UTC by jyothishnt

https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2599

Integrated

- tests
- linting using flake8
- formatting using black

2024-08-19 13:20 UTC, azangru commented on .gitlab-ci.yml
> +  - test
Should `lint` and `format` really be independent stages / jobs? Considering this is CI/CD environment, and no changes to the source code are going to be committed, is there any reason to run the formatter at all? And doesn't it make sense to run the linter as part of the test job?

2024-08-19 15:51 UTC, jonk-ebi commented on .gitlab-ci.yml
> +Format:
Without a push command this stage will correct the code in the runner but nothing else.

Personally I don't think it is a good idea to run code modification stages in CI. 
My reasons are :-
- The author ends up with a slightly different version of the code to the PR
- Can introduce hard to discover errors 

Black should be ran as a precommit hook or on save in your IDE.

2024-08-20 08:55 UTC, kamaldodiya requested changes

2024-08-20 08:55 UTC, kamaldodiya commented on app/core/config.py
>  ENSEMBL_URL = config("ENSEMBL_URL", cast=str, default="http://beta.ensembl.org")
https ?

2024-08-20 08:55 UTC, kamaldodiya commented on requirements.txt
> +black=24.8.0
Should this be in requirements-dev.txt I don't think this is needed in production for example https://github.com/Ensembl/ensembl-web-tools-api/blob/dev/requirements-dev.txt

2024-08-20 12:37 UTC, kamaldodiya commented on requirements.txt
> +flake8==7.1.1
Is this still needed in production build ?

2024-09-03 08:45 UTC, kamaldodiya approved these changes

2024-09-04 13:26 UTC, azangru approved these changes

2024-09-04 13:32 UTC, merged